### ISSUE TITLE
RTL support for bootswatch themes

### ISSUE THREAD

**Issue by Exlord** [morteza/bootstrap-rtl#13]
Hi, 
can you provide RTL support for bootswatch themes too ?
this version is working almost right with bootswatch themes but not 100%, it only needs miner adjustments.

it would be appreciated.

**Comment by elad** [comment]
@morteza this is actually very easy to do. All it requires is *removing* some definitions that don't pertain to right-to-left.

For example, the Cosmo theme has square (as opposed to rounded) corners on nav pills. Corner rounding has nothing to do with right-to-left, so removing the relevant lines in `navs-rtl.less` makes it work well.

Apart from that, it can be used just fine with Bootswatch themes.

Would you accept pull requests that remove this kind of stuff?

**Comment by morteza** [comment]
Sure, all relevant and ready-to-merge pull requests will be accepted ;-)
