### ISSUE TITLE
Question/help: angular app with both rtl and ltr pages

### ISSUE THREAD

**Issue by misamae** [morteza/bootstrap-rtl#132]
Is it possible to have both rtl and ltr on the same site/application? 

I have an angular app that is mainly rtl. However, I need to do ltr for a few views/components. Is this possible? If that is the case is there an example I can take a few ideas?

**Comment by morteza** [comment]
bootstrap-rtl works like a them over regular bootstrap. So you might want to use `ng-href` or preload both. Here: https://stackoverflow.com/questions/25568801/angularjs-switch-css-theme-on-user-selection

**Comment by misamae** [comment]
Thanks

**Comment by dtasamo** [comment]
yes something like that cause your code i add in the costum css he work he chang every thin in my website 
but he chang in all languge but i just need rtl in arabic lunguge please help me where and how i make your code in arabic lunguge and if you want we can contact in facebook or something and thanks
