### ISSUE TITLE
Any plan for Bootstrap 4 RTL Feature ? When It will Release ?

### ISSUE THREAD

**Issue by kishorsathe** [morteza/bootstrap-rtl#134]

**Comment by morteza** [comment]
No plan yet :-)

**Comment by kishorsathe** [comment]
@morteza do you have any update on Bootstrap 4 RTL support? 

Regards,
kishor

**Comment by morteza** [comment]
Unfortunately no, not by me. But you can already find several alternatives for v4 :-)
