### ISSUE TITLE
'.dropdown-menu-right' and '.dropdown-menu-left' are ignored

### ISSUE THREAD

**Issue by rekino** [morteza/bootstrap-rtl#17]
Hi @morteza,

According to <a href="http://getbootstrap.com/components/#dropdowns-alignment">bootstrap docs</a>, in order to right/left align the dropdown menu, '.dropdown-menu-right'/'.dropdown-menu-left' classes should be used. After linking the RTL theme, these classes were ignored.

The work around right now is to add '.pull-right'/'.pull-left' to the ''.dropdown-menu' element, but this solution is deprecated according to the docs.

**Comment by theyuv** [comment]
What is the recommended fix for this? If we apply the class `dropdown-menu-right` on an element, how do we get the reverse of that to be applied when using bootstrap-rtl.css?
