### ISSUE TITLE
Wrong width of datepicker

### ISSUE THREAD

**Issue by dev-mfm** [morteza/bootstrap-rtl#35]
![datepicker](https://cloud.githubusercontent.com/assets/8669854/4169080/244657f4-3524-11e4-9963-6d36ae0c90c7.jpeg)

when adding bootstrap-rtl the width of the datepicker is get increased. I use this tool for datepicker https://github.com/eternicode/bootstrap-datepicker and it works fine without the bootstrap-rtl

**Comment by bashirnoori** [comment]
add this CSS code to prevent from extra large size of datepicker:
`.datepicker-dropdown {max-width: 300px;}`

**Comment by xbox2007** [comment]
hello 
please try this one , 

`<style>         
    .datepicker {
        direction: rtl;
		}             
    .datepicker.dropdown-menu {
		right: initial;             
      }     
</style>`
