### ISSUE TITLE
Is there any Sass port to this RTL version?

### ISSUE THREAD

**Issue by zukilover** [morteza/bootstrap-rtl#36]
It would be great to have one.

**Comment by geminorum** [comment]
how about using the [convertor](https://github.com/twbs/bootstrap-sass#upstream-converter) on [bootstrap-sass](https://github.com/twbs/bootstrap-sass)?

**Comment by cho-is** [comment]
I am about to finish a port to SASS. You want me to do a pull request?

**Comment by morteza** [comment]
It seems good to me. I'm a little out of the map for next month but will consider it. However all contributions are appreciated.
