### ISSUE TITLE
Update cdnjs to v3.3.1

### ISSUE THREAD

**Issue by morteza** [morteza/bootstrap-rtl#50]
Currently the bootstrap-rtl version of cdnjs is stuck at v3.2.0-rc2, which is too old. Somebody has to send a pull request for the updated version.

Corresponding distribution packages for cdnjs are available under `dist/cdnjs/*` directory.

**Comment by nekofar** [comment]
I suggest you to use [RawGit](https://rawgit.com/) instead. I just made a pull request based on it. :+1:
