### ISSUE TITLE
pull-right and pull-left classes missing in css file

### ISSUE THREAD

**Issue by mewsoft** [morteza/bootstrap-rtl#52]
First, thank you for your excellent effort in doing correct RTL support for bootstrap.

The css file is missing these two important classes, they should be like this:
```
.pull-right {
  float: left !important;
}
.pull-left {
  float: right !important;
}
```
This fixed badges and navs etc.

**Comment by morteza** [comment]
Duplicate of #32, and #49. The semantics for `right` and `left` remain the same to avoid confusion.
