### ISSUE TITLE
Extra class added to .has-feedback .form-control

### ISSUE THREAD

**Issue by mewsoft** [morteza/bootstrap-rtl#58]
I think you have added extra css attribute padding-right: 12px; to the class .has-feedback .form-control which does not exist in the original bootstrap.css.

```
.has-feedback .form-control {
    padding-left: 42.5px;
    padding-right: 12px;
}
```
My current temp fix is:
```
.has-feedback .form-control {
	padding-right: 0px;
}
```

**Comment by morteza** [comment]
You can find it on the line 2740 of the original `bootstrap.css` file (v3.3.1). It's there to ensure icons don't overlap texts.

I don't get what you fixed. Here is a practical snippet for feedbacks:

```html
<div class="form-group has-error has-feedback">
  <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
  <div class="col-sm-10">
    <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    <span class="glyphicon glyphicon-remove form-control-feedback"></span>
  </div>
</div>
```

**Comment by mewsoft** [comment]
May be I am wrong, line 2740 of the original bootstrap.css dist file (v3.3.1) show me this:

![bootstrap-rtl-fix](https://cloud.githubusercontent.com/assets/7512085/5855895/df92aed4-a245-11e4-830d-2e291206e08f.jpg)

which you converted correctly as:

```
.form-horizontal .has-feedback .form-control-feedback {
  left: 15px;
  right: auto;
}
```

The only classes for this in the original file at line 2535 is:
```
.has-feedback {
  position: relative;
}
.has-feedback .form-control {
  padding-right: 42.5px;
}
```
![bootstrap-rtl-fix1](https://cloud.githubusercontent.com/assets/7512085/5855983/55cf2a18-a247-11e4-9c7c-7b86e114d23f.jpg)

**Comment by morteza** [comment]
Ok. In your version of bootstrap it's line 2538. It's there to prevent text and icon overlapping.

Don't make a big deal out of this. I'm clear what exactly you are requesting and what the issue is. This is not a discussion board. Please be precise about what the issue is, and what is requested, and for what problems you are proposing the solution. Be clear, and search the web before submitting something here.
