### ISSUE TITLE
problem with label in radio button

### ISSUE THREAD

**Issue by saghian** [morteza/bootstrap-rtl#59]
dear Morteza
i have a problem with label in radio button.
i want create form with in line radio button like attachment file.
best regards

My code:

            <label class="radio-inline">
                    <input type="radio" name="radioUserType">دانشجو
            </label>
            <label class="radio-inline">
                    <input type="radio" name="radioUserType"> کارشناس
            </label>

![radio bootstrap](https://cloud.githubusercontent.com/assets/7473246/5891405/d3628372-a4a8-11e4-9dc5-2ecf1d58536c.png)

**Comment by saghian** [comment]
if you add    margin-right: -20px    in   input type="radio"   display correct  :  

![radio bootstrap 2](https://cloud.githubusercontent.com/assets/7473246/5891446/43f01440-a4ab-11e4-83bd-16ea25666570.png)

**Comment by morteza** [comment]
You might need to update your bootstrap-rtl. Right margin has been added since 12b4a62.
