### ISSUE TITLE
border-right of .input-group:first-child is incorrect

### ISSUE THREAD

**Issue by willi1s** [morteza/bootstrap-rtl#60]
With an input group addon, the right border appears incorrect.

![input_group_addon_right_border_error](https://cloud.githubusercontent.com/assets/10740563/5936962/ca278056-a6e1-11e4-8d15-ec8db2c2d80d.png)

Using the Chrome dev tools I can see that disabling .input-group-addon:first-child { border-right: 0 } from bootstrap.css results in a correct display:

![input_group_addon_right_border_fixed](https://cloud.githubusercontent.com/assets/10740563/5936977/fd09a968-a6e1-11e4-9d4c-6835437dbafc.png)

I guess this should be overridden in bootstrap-rtl.css

**Comment by ahmadramadan** [comment]
I have the same issue

**Comment by morteza** [comment]
I might caused by a fix to #48.
