### ISSUE TITLE
npm ERR! 404 'bootstrap-rtl' is not in the npm registry.

### ISSUE THREAD

**Issue by obadasemary** [morteza/bootstrap-rtl#61]
when npm install

npm ERR! 404 'bootstrap-rtl' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "bootstrap-rtl"
npm ERR! cwd /home/obada/WebstormProjects/Fahras
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/obada/WebstormProjects/Fahras/npm-debug.log
npm ERR! not ok code 0

**Comment by obadasemary** [comment]
npm ERR! 404 'bootstrap-rtl' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "bootstrap-rtl"
npm ERR! cwd /home/obada/WebstormProjects/Fahras
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/obada/WebstormProjects/Fahras/npm-debug.log
npm ERR! not ok code 0

**Comment by morteza** [comment]
It was not published to npmjs. It is now available at https://www.npmjs.com/package/bootstrap-rtl

**Comment by obadasemary** [comment]
when i 
Run bower install bootstrap-rtl 

and then 

Run npm install

my output is =>

npm ERR! Error: No compatible version found: bootstrap-rtl@'>=3.2.0-0 <3.3.0-0'
npm ERR! Valid install targets:
npm ERR! ["3.3.1","3.3.2-rc1"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at next (/usr/share/npm/lib/cache.js:698:17)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/obada/WebstormProjects/Fahras
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 200 https://registry.npmjs.org/angular-route
npm http GET https://registry.npmjs.org/angular-route/-/angular-route-1.3.13.tgz
npm http 200 https://registry.npmjs.org/angular-route/-/angular-route-1.3.13.tgz
npm http 200 https://registry.npmjs.org/angular
npm http GET https://registry.npmjs.org/angular/-/angular-1.3.13.tgz
npm http 200 https://registry.npmjs.org/angular/-/angular-1.3.13.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/obada/WebstormProjects/Fahras/npm-debug.log
npm ERR! not ok code 0

**Comment by morteza** [comment]
Update your npm. It should be at least v1.4.3 to support the caret ^ versioning.

**Comment by obadasemary** [comment]
how can i update it !!

**Comment by obadasemary** [comment]
@morteza 
my v 1.3.10
how can i update it

**Comment by obadasemary** [comment]
after i run npm update 
the v 1.3.10
again :(
