### ISSUE TITLE
custom grid size

### ISSUE THREAD

**Issue by zxiest** [morteza/bootstrap-rtl#69]
Hello =)

I have a custom grid size with bootstrap but it looks like bootstrap-rtl is basing its grid on the 12 grid system. I have the rtl's stylesheet included after bootstrap's.

Any suggestions?

**Comment by zxiest** [comment]
I have done the following changes in bootstrap/less/variables.less and recompiled.

    @grid-columns:              15;
    @grid-gutter-width:         10px;

**Comment by morteza** [comment]
This RTL theme uses same variables from same file to generate grids. Put your customized bootstrap source codes inside `bootstrap/` directory of this project, and then recompile bootstrap-rtl with `grunt`. That's all.
