### ISSUE TITLE
input group border color

### ISSUE THREAD

**Issue by afattahi54** [morteza/bootstrap-rtl#71]
When applying the bootstrap-rtl the input-group border will be override. May be something wrong with

.input-group-addon:first-child{
	border-left:0;
	border-right:1px solid
}

The firebug shows that the bootstrap overrided value is   -moz-use-text-color !!!

I am using bootstrap-rtl-3.3.4-rc1.

PS: This happens for .input-group-addon:last-child too

**Comment by morteza** [comment]
Duplicate of #63, #60, #48. It is also mentioned in #66 and several others.

**Comment by afattahi54** [comment]
Thanks! I am testing it on version rtl-3.3.4-rc1, I guessed this have been closed in 3.3.1. Am I correct?! I wonder why I still see this issue in 3.3.4-rc1 :)
