### ISSUE TITLE
About CSS and JS files

### ISSUE THREAD

**Issue by akram1** [morteza/bootstrap-rtl#81]
Do I need to include the rtl js files: html5shiv.js, holder.js, query.min.js, respond.min.js (why they are different from the orginal it is called bootstrap.js)? 

If I include rtl css, will rtl and ltr work together (no overriding)?

**Comment by morteza** [comment]
1. No, the rtl theme provided here only needs a single css file to be included, `bootstrap-rtl.css` (or minimized `bootstrap-rtl.min.css`.

2. No, but it seems easy to set up a mechanism to switch rtl views on of off, by removing the rtl css file on ltr views. The remaining stuff are all in ltr direction.
